version: '3.9'

services:
  backend:
    container_name: app_backend
    build: ./backend
    ports: -3001:3001
    working_dir: /app-backend
    volumes:
      - ./src:/app-backend/src
  frontend:
    container_name: app_frontend
    build: ./frontend
    ports: -3000:3000
    working_dir: /app-frontend
    volumes: -./src:/app-frontend/src
    depends_on:
      - backend
